def test_movements(puzzle):
    puzzle.move_up('0')
    puzzle.print()
    puzzle.move_up('0')
    puzzle.print()
    puzzle.move_down('0')
    puzzle.print()
    puzzle.move_down('3')
    puzzle.print()
    puzzle.move_left('0')
    puzzle.print()
    puzzle.move_left('8')
    puzzle.print()
    puzzle.move_right('3')
    puzzle.print()
    puzzle.move_right('6')
    puzzle.print()